### ISSUE TITLE
resizImageIcon dentro de delete dialog. 

### ISSUE THREAD

**Issue by Roberto-Garijo** [Ballesito/OpusList#1]
Dentro de "DeleteDialog" tienes un metodo que nunca es usado.
![image](https://user-images.githubusercontent.com/77688938/141133593-57490e5f-29ec-4ecc-aaec-7f16898ab55d.png)

**Comment by Ballesito** [comment]
Ya he hecho el push solucionandolo. Mira a ver si hay algun error.
