### ISSUE TITLE
Insertar vacío

### ISSUE THREAD

**Issue by AlexisEvol** [Ballesito/OpusList#3]
El programa te permite insertar vacío.

Para cambiarlo yo haría que cada casilla requiera x cantidad de caracteres.

![image](https://user-images.githubusercontent.com/77688934/141705193-b109f09a-adfc-4a8f-9874-7b33eba83263.png)

**Comment by Ballesito** [comment]
Ya he solucionado el Issue, mira a ver si vuelve a ocurrir y me comentas.

**Comment by AlexisEvol** [comment]
It's showing a message that you can't insert an empty record, good job!
