### ISSUE TITLE
The project won't let me insert

### ISSUE THREAD

**Issue by pauprats2002** [Ballesito/OpusList#6]
When I try to insert a new artwork, the record field always has a record from the list.
![image](https://user-images.githubusercontent.com/77688104/141858967-19a2a96b-1993-4cf6-bc8e-aa7e5e3f6b6a.png)

**Comment by Ballesito** [comment]
I've done that you can't write the register because  generates randomly and if the generated code already exists, generates a new one.

**Comment by pauprats2002** [comment]
Okey, perfect
